# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51ab0f883b773346f7b14a781cda5d271daa4b29290e09828f7dfaf75890b883b0130e0df2f2da859ff45a17dc4fd56067b5129c2cc2449ce1908b360cdb43ca

test:
  secret_key_base: f2e6586839f3a1bc1cc8117d44c823ee17ad29c269cf880b33cba9272fa06da3f4dfe281eb3a20e05173a745bd2ad166cc4c31472e456ee6768a04de629ede9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
